"use client";

import { useState } from "react";

interface Factor {
  name: string;
  score: number;
  explanation: string;
}

interface Comparable {
  domain: string;
  soldPrice: number;
  year: number;
}

interface Valuation {
  domain: string;
  estimatedValue: {
    low: number;
    mid: number;
    high: number;
    currency: string;
  };
  grade: string;
  factors: Factor[];
  summary: string;
  comparables: Comparable[];
  suggestions: string[];
}

function formatUSD(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(1)}K`;
  return `$${n.toLocaleString()}`;
}

function gradeColor(grade: string): string {
  const g = grade.replace("+", "").replace("-", "");
  if (g === "A") return "bg-emerald-500";
  if (g === "B") return "bg-green-500";
  if (g === "C") return "bg-yellow-500";
  if (g === "D") return "bg-orange-500";
  return "bg-red-500";
}

function gradeTextColor(grade: string): string {
  const g = grade.replace("+", "").replace("-", "");
  if (g === "A") return "text-emerald-400";
  if (g === "B") return "text-green-400";
  if (g === "C") return "text-yellow-400";
  if (g === "D") return "text-orange-400";
  return "text-red-400";
}

function barColor(score: number): string {
  if (score >= 8) return "bg-emerald-500";
  if (score >= 6) return "bg-green-500";
  if (score >= 4) return "bg-yellow-500";
  if (score >= 2) return "bg-orange-500";
  return "bg-red-500";
}

export default function Home() {
  const [domain, setDomain] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<Valuation | null>(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!domain.trim()) return;

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const res = await fetch("/api/valuate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ domain: domain.trim() }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Something went wrong");
        return;
      }

      setResult(data);
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  function copyReport() {
    if (!result) return;
    const report = `Domain Valuation Report -- ${result.domain}
========================================
Estimated Value: ${formatUSD(result.estimatedValue.low)} - ${formatUSD(result.estimatedValue.high)}
Most Likely: ${formatUSD(result.estimatedValue.mid)}
Grade: ${result.grade}

${result.summary}

Factors:
${result.factors.map((f) => `  ${f.name}: ${f.score}/10 -- ${f.explanation}`).join("\n")}

Comparable Sales:
${result.comparables.map((c) => `  ${c.domain} -- $${c.soldPrice.toLocaleString()} (${c.year})`).join("\n")}

Suggestions:
${result.suggestions.map((s) => `  - ${s}`).join("\n")}

-- Generated by DomainIQ`;

    navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="border-b border-[#2a2a2a] px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-indigo-500 flex items-center justify-center font-bold text-sm">
              IQ
            </div>
            <h1 className="text-xl font-bold">DomainIQ</h1>
          </div>
          <a
            href="https://github.com/maxilylm/su-domainiq"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#888] hover:text-white transition-colors text-sm flex items-center gap-1.5"
          >
            <svg
              className="w-4 h-4"
              fill="currentColor"
              viewBox="0 0 24 24"
            >
              <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z" />
            </svg>
            GitHub
          </a>
        </div>
      </header>

      {/* Main */}
      <main className="flex-1 px-6 py-12">
        <div className="max-w-4xl mx-auto">
          {/* Hero */}
          <div className="text-center mb-10">
            <h2 className="text-3xl sm:text-4xl font-bold mb-3">
              AI Domain Name Valuator
            </h2>
            <p className="text-[#888] text-lg">
              Enter any domain name and get an instant AI-powered market
              valuation
            </p>
          </div>

          {/* Input */}
          <form
            onSubmit={handleSubmit}
            className="flex flex-col sm:flex-row gap-3 max-w-xl mx-auto mb-12"
          >
            <div className="flex-1 relative">
              <input
                type="text"
                value={domain}
                onChange={(e) => setDomain(e.target.value)}
                placeholder="example.com"
                className="w-full bg-[#111] border border-[#2a2a2a] rounded-lg px-4 py-3 text-white placeholder:text-[#555] focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-colors"
                disabled={loading}
              />
              <span className="absolute right-4 top-1/2 -translate-y-1/2 text-[#444] text-sm pointer-events-none">
                .com
              </span>
            </div>
            <button
              type="submit"
              disabled={loading || !domain.trim()}
              className="bg-indigo-500 hover:bg-indigo-600 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold px-8 py-3 rounded-lg transition-all cursor-pointer whitespace-nowrap"
            >
              {loading ? (
                <span className="flex items-center gap-2">
                  <svg
                    className="animate-spin w-4 h-4"
                    viewBox="0 0 24 24"
                    fill="none"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    />
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                    />
                  </svg>
                  Valuating...
                </span>
              ) : (
                "Valuate"
              )}
            </button>
          </form>

          {/* Error */}
          {error && (
            <div className="max-w-xl mx-auto mb-8 bg-red-500/10 border border-red-500/30 rounded-lg px-4 py-3 text-red-400 text-center animate-fade-in">
              {error}
            </div>
          )}

          {/* Results */}
          {result && (
            <div className="space-y-6 animate-fade-in">
              {/* Value + Grade */}
              <div className="bg-[#111] border border-[#2a2a2a] rounded-xl p-6 sm:p-8">
                <div className="flex flex-col sm:flex-row items-center justify-between gap-6">
                  <div className="text-center sm:text-left">
                    <p className="text-[#888] text-sm mb-1 uppercase tracking-wider">
                      Estimated Value
                    </p>
                    <div className="flex items-baseline gap-2 flex-wrap justify-center sm:justify-start">
                      <span className="text-[#888] text-xl">
                        {formatUSD(result.estimatedValue.low)}
                      </span>
                      <span className="text-[#555]">--</span>
                      <span className="text-3xl sm:text-4xl font-bold text-indigo-400 animate-pulse-glow rounded-lg px-2">
                        {formatUSD(result.estimatedValue.mid)}
                      </span>
                      <span className="text-[#555]">--</span>
                      <span className="text-[#888] text-xl">
                        {formatUSD(result.estimatedValue.high)}
                      </span>
                    </div>
                    <p className="text-[#555] text-xs mt-1">
                      low -- most likely -- high
                    </p>
                  </div>
                  <div className="flex flex-col items-center">
                    <p className="text-[#888] text-sm mb-1 uppercase tracking-wider">
                      Grade
                    </p>
                    <div
                      className={`w-16 h-16 rounded-xl ${gradeColor(result.grade)} flex items-center justify-center`}
                    >
                      <span className="text-2xl font-black text-white">
                        {result.grade}
                      </span>
                    </div>
                  </div>
                </div>
                <p className="mt-6 text-[#aaa] leading-relaxed">
                  {result.summary}
                </p>
              </div>

              {/* Factors */}
              <div className="bg-[#111] border border-[#2a2a2a] rounded-xl p-6 sm:p-8">
                <h3 className="text-lg font-semibold mb-5">
                  Valuation Factors
                </h3>
                <div className="space-y-4">
                  {result.factors.map((factor, i) => (
                    <div
                      key={factor.name}
                      className={`animate-slide-in opacity-0 stagger-${i + 1}`}
                    >
                      <div className="flex items-center justify-between mb-1.5">
                        <span className="font-medium text-sm">
                          {factor.name}
                        </span>
                        <span
                          className={`text-sm font-bold ${gradeTextColor(factor.score >= 8 ? "A" : factor.score >= 6 ? "B" : factor.score >= 4 ? "C" : factor.score >= 2 ? "D" : "F")}`}
                        >
                          {factor.score}/10
                        </span>
                      </div>
                      <div className="w-full bg-[#1a1a1a] rounded-full h-2.5 mb-1.5">
                        <div
                          className={`h-2.5 rounded-full animate-bar-fill ${barColor(factor.score)}`}
                          style={{ width: `${factor.score * 10}%` }}
                        />
                      </div>
                      <p className="text-[#888] text-xs">
                        {factor.explanation}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Comparables */}
              {result.comparables && result.comparables.length > 0 && (
                <div className="bg-[#111] border border-[#2a2a2a] rounded-xl p-6 sm:p-8 animate-fade-in">
                  <h3 className="text-lg font-semibold mb-4">
                    Comparable Sales
                  </h3>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="text-[#888] border-b border-[#2a2a2a]">
                          <th className="text-left py-2 pr-4 font-medium">
                            Domain
                          </th>
                          <th className="text-right py-2 pr-4 font-medium">
                            Sale Price
                          </th>
                          <th className="text-right py-2 font-medium">Year</th>
                        </tr>
                      </thead>
                      <tbody>
                        {result.comparables.map((comp) => (
                          <tr
                            key={comp.domain}
                            className="border-b border-[#1a1a1a] last:border-0"
                          >
                            <td className="py-2.5 pr-4 text-indigo-400 font-medium">
                              {comp.domain}
                            </td>
                            <td className="py-2.5 pr-4 text-right text-white">
                              ${comp.soldPrice.toLocaleString()}
                            </td>
                            <td className="py-2.5 text-right text-[#888]">
                              {comp.year}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {/* Suggestions */}
              {result.suggestions && result.suggestions.length > 0 && (
                <div className="bg-[#111] border border-[#2a2a2a] rounded-xl p-6 sm:p-8 animate-fade-in">
                  <h3 className="text-lg font-semibold mb-4">
                    Improvement Suggestions
                  </h3>
                  <ul className="space-y-2.5">
                    {result.suggestions.map((s, i) => (
                      <li key={i} className="flex items-start gap-3 text-sm">
                        <span className="text-indigo-400 mt-0.5 shrink-0">
                          &rarr;
                        </span>
                        <span className="text-[#aaa]">{s}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Copy Report */}
              <div className="flex justify-center">
                <button
                  onClick={copyReport}
                  className="bg-[#1a1a1a] border border-[#2a2a2a] hover:border-indigo-500/50 text-[#aaa] hover:text-white px-6 py-2.5 rounded-lg text-sm transition-all cursor-pointer"
                >
                  {copied ? "Copied to clipboard!" : "Copy full report"}
                </button>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#2a2a2a] px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between text-xs text-[#555]">
          <span>DomainIQ</span>
          <span>
            Powered by{" "}
            <a
              href="https://groq.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#888] hover:text-white transition-colors"
            >
              Groq
            </a>
          </span>
        </div>
      </footer>
    </div>
  );
}
